### ISSUE TITLE
question of DEG masking

### ISSUE THREAD

**Issue by Susan920715** [bm2-lab/STAMP#2]
Hi, great work! I have a few questions regarding the implementation.

In the article, the template diagram mentions the masking of DEG, but I couldn’t locate the corresponding part in the code. Instead, I only found code that masks zero values. Could you clarify where the DEG masking is implemented?

Also, I noticed that the output from First_layer in TaskCombineLayer doesn’t appear to be used in the subsequent two tasks. Could you explain the role of First_layer in the multitasking setup?

Thank you!

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest. You can find the answers from the reply of previous issues. As for your main concerns, the first subtask’ output can also be directly used to supervise the subsequent subtasks, however, this may also introduce more noise in the level of labels compared to using the ground truth DEG labels.

**Comment by Susan920715** [comment]
Thanks a lot!  I still have a question, could you please give the code of the benchamrk part, especially the parameter setting when using other algorithms。

**Comment by GaoYiChengTJ** [comment]
We used the default parameter settings for other methods, and you can find the detailed information of modified version of other methods in the supplementary information.

**Comment by Susan920715** [comment]
Thank you very much. I think the "Ontology-based+STAMP" models mentioned in the article are better than others, but I didn't see the specific description of how to transform these models in the attachment. If it is convenient, Could you please tell me the code of this part of the model (" Ontology-based+STAMP ")? Thank you very much! If convenient, you can send email to: wangjm23@mails.tsinghua.edu.cn

**Comment by GaoYiChengTJ** [comment]
Hi, we have uploaded the core codes of modified GEARS and CPA to the Supp_code in our Github. Thanks for your interest.
