### ISSUE TITLE
Missing codes and data to reproduce Fig.5 in the paper

### ISSUE THREAD

**Issue by chinaliye** [bm2-lab/STAMP#3]
Thanks for developing such a great tool for perturbation response prediction. However, I can't reproduce the figure 5 in your published paper with codes and data in this github repository. I will appreciate it if you can share the codes which should reproduce this figure.
![image](https://github.com/user-attachments/assets/08c4c79f-7a66-41e9-a1ae-d47be86d673f)

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest. We have uploaded the GI experiment-related code and result data to the Supp_code in our Github. The results generated by the GEARS and STAMP can be obtained by running the GERAS and STAMP by following the steps in our Supplementary information.
