### ISSUE TITLE
Two datasets used for 'Predicting multiple-genetic-perturbation outcomes' are actually single-genetic-perturbed

### ISSUE THREAD

**Issue by chinaliye** [bm2-lab/STAMP#4]
Hi, I read your recently published paper in which I saw 'To conduct this comprehensive comparison, we utilized preprocessed data from three distinct datasets: the PRJNA551220 dataset, the Perturb-CITE-seq dataset and the PRJNA787633 dataset.' However, after I checked the above datasets, I found that two datasets (i.e. Perturb-CITE-seq dataset and the PRJNA787633 dataset) were single-genetic-perturbed actually. Specifically, I extracted the obs dataframe from the h5ad files and found that each cell has only one gene perturbed. Please see the following graphs:
![image](https://github.com/user-attachments/assets/63fb4db9-b75d-426a-94f0-a2b03bbe66da)
![image](https://github.com/user-attachments/assets/22f56522-c5c6-4358-bfd9-e8fc61a83b51)
I will appreciate it if you can point out my misunderstanding about the above datasets and share your processed datasets which can be downloaded using git-lfs.

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest. The preprocessed datasets you indicated above are not used in our study and you can download these two datasets from their original studies (see Data availability in our paper). And you can find the preprocessed datasets used in this study in our Zenodo (https://zenodo.org/records/12779567).
