### ISSUE TITLE
Query data containing specific transcription

### ISSUE THREAD

**Issue by Panda-myj** [bm2-lab/STAMP#5]
Hello, thank you very much for the processed data. But I found that the X matrix of the data is all 0/1. Is this because the paper does not involve the use of transcription profiles, so it only provides this form. Could you please provide the corresponding specific transcription profile data after processing? Thank you so much!

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest. Yes, the X matrix is not used in our study, we used the matrix in layers to perform training and testing. I think it would be better to download the specific transcription raw data according to the data availability part of our article, as our matrix can not save transcription data for each single-cell.

**Comment by Panda-myj** [comment]
all right, thank you!
