### ISSUE TITLE
How to through scGPT to get the gene embedding?

### ISSUE THREAD

**Issue by Panda-myj** [bm2-lab/STAMP#6]
Thank you very much for your work. But I have some doubts about gene embedding here. Is the gene embedding of a dataset that is the same?(because at one dataset, singlecells have same name.) 
Can you provide the code of the processed data through scGPT to get the gene embedding? Whether the input of the scGPT is gene transcriptional profiling? Thank you very much!

**Comment by GaoYiChengTJ** [comment]
Thanks for your interest. We directly used the token embeddings of scGPT here, which you can obtained in the scGPT’s model weights.
